// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	store "kronus.dev/commbadge_api/store"
)

// MockTicketRepository is an autogenerated mock type for the TicketRepository type
type MockTicketRepository struct {
	mock.Mock
}

type MockTicketRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTicketRepository) EXPECT() *MockTicketRepository_Expecter {
	return &MockTicketRepository_Expecter{mock: &_m.Mock}
}

// AddMessage provides a mock function with given fields: ctx, ticketID, userID, body, isAdmin
func (_m *MockTicketRepository) AddMessage(ctx context.Context, ticketID string, userID string, body string, isAdmin bool) (*store.TicketMessage, error) {
	ret := _m.Called(ctx, ticketID, userID, body, isAdmin)

	if len(ret) == 0 {
		panic("no return value specified for AddMessage")
	}

	var r0 *store.TicketMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) (*store.TicketMessage, error)); ok {
		return rf(ctx, ticketID, userID, body, isAdmin)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) *store.TicketMessage); ok {
		r0 = rf(ctx, ticketID, userID, body, isAdmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.TicketMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, bool) error); ok {
		r1 = rf(ctx, ticketID, userID, body, isAdmin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_AddMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMessage'
type MockTicketRepository_AddMessage_Call struct {
	*mock.Call
}

// AddMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID string
//   - userID string
//   - body string
//   - isAdmin bool
func (_e *MockTicketRepository_Expecter) AddMessage(ctx interface{}, ticketID interface{}, userID interface{}, body interface{}, isAdmin interface{}) *MockTicketRepository_AddMessage_Call {
	return &MockTicketRepository_AddMessage_Call{Call: _e.mock.On("AddMessage", ctx, ticketID, userID, body, isAdmin)}
}

func (_c *MockTicketRepository_AddMessage_Call) Run(run func(ctx context.Context, ticketID string, userID string, body string, isAdmin bool)) *MockTicketRepository_AddMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *MockTicketRepository_AddMessage_Call) Return(_a0 *store.TicketMessage, _a1 error) *MockTicketRepository_AddMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_AddMessage_Call) RunAndReturn(run func(context.Context, string, string, string, bool) (*store.TicketMessage, error)) *MockTicketRepository_AddMessage_Call {
	_c.Call.Return(run)
	return _c
}

// AdminListAll provides a mock function with given fields: ctx, limit, offset
func (_m *MockTicketRepository) AdminListAll(ctx context.Context, limit int, offset int) ([]store.SupportTicket, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for AdminListAll")
	}

	var r0 []store.SupportTicket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]store.SupportTicket, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []store.SupportTicket); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.SupportTicket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_AdminListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminListAll'
type MockTicketRepository_AdminListAll_Call struct {
	*mock.Call
}

// AdminListAll is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockTicketRepository_Expecter) AdminListAll(ctx interface{}, limit interface{}, offset interface{}) *MockTicketRepository_AdminListAll_Call {
	return &MockTicketRepository_AdminListAll_Call{Call: _e.mock.On("AdminListAll", ctx, limit, offset)}
}

func (_c *MockTicketRepository_AdminListAll_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockTicketRepository_AdminListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockTicketRepository_AdminListAll_Call) Return(_a0 []store.SupportTicket, _a1 error) *MockTicketRepository_AdminListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_AdminListAll_Call) RunAndReturn(run func(context.Context, int, int) ([]store.SupportTicket, error)) *MockTicketRepository_AdminListAll_Call {
	_c.Call.Return(run)
	return _c
}

// AdminTicketCount provides a mock function with given fields: ctx
func (_m *MockTicketRepository) AdminTicketCount(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AdminTicketCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_AdminTicketCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminTicketCount'
type MockTicketRepository_AdminTicketCount_Call struct {
	*mock.Call
}

// AdminTicketCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTicketRepository_Expecter) AdminTicketCount(ctx interface{}) *MockTicketRepository_AdminTicketCount_Call {
	return &MockTicketRepository_AdminTicketCount_Call{Call: _e.mock.On("AdminTicketCount", ctx)}
}

func (_c *MockTicketRepository_AdminTicketCount_Call) Run(run func(ctx context.Context)) *MockTicketRepository_AdminTicketCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTicketRepository_AdminTicketCount_Call) Return(_a0 int, _a1 error) *MockTicketRepository_AdminTicketCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_AdminTicketCount_Call) RunAndReturn(run func(context.Context) (int, error)) *MockTicketRepository_AdminTicketCount_Call {
	_c.Call.Return(run)
	return _c
}

// AdminUpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *MockTicketRepository) AdminUpdateStatus(ctx context.Context, id string, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for AdminUpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTicketRepository_AdminUpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminUpdateStatus'
type MockTicketRepository_AdminUpdateStatus_Call struct {
	*mock.Call
}

// AdminUpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - status string
func (_e *MockTicketRepository_Expecter) AdminUpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockTicketRepository_AdminUpdateStatus_Call {
	return &MockTicketRepository_AdminUpdateStatus_Call{Call: _e.mock.On("AdminUpdateStatus", ctx, id, status)}
}

func (_c *MockTicketRepository_AdminUpdateStatus_Call) Run(run func(ctx context.Context, id string, status string)) *MockTicketRepository_AdminUpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTicketRepository_AdminUpdateStatus_Call) Return(_a0 error) *MockTicketRepository_AdminUpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTicketRepository_AdminUpdateStatus_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTicketRepository_AdminUpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, userID, subject, body
func (_m *MockTicketRepository) Create(ctx context.Context, userID string, subject string, body string) (*store.SupportTicket, error) {
	ret := _m.Called(ctx, userID, subject, body)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *store.SupportTicket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*store.SupportTicket, error)); ok {
		return rf(ctx, userID, subject, body)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *store.SupportTicket); ok {
		r0 = rf(ctx, userID, subject, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.SupportTicket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, userID, subject, body)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTicketRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - subject string
//   - body string
func (_e *MockTicketRepository_Expecter) Create(ctx interface{}, userID interface{}, subject interface{}, body interface{}) *MockTicketRepository_Create_Call {
	return &MockTicketRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, subject, body)}
}

func (_c *MockTicketRepository_Create_Call) Run(run func(ctx context.Context, userID string, subject string, body string)) *MockTicketRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTicketRepository_Create_Call) Return(_a0 *store.SupportTicket, _a1 error) *MockTicketRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_Create_Call) RunAndReturn(run func(context.Context, string, string, string) (*store.SupportTicket, error)) *MockTicketRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTicketRepository) GetByID(ctx context.Context, id string) (*store.SupportTicket, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *store.SupportTicket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*store.SupportTicket, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *store.SupportTicket); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.SupportTicket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTicketRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTicketRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTicketRepository_GetByID_Call {
	return &MockTicketRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTicketRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockTicketRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTicketRepository_GetByID_Call) Return(_a0 *store.SupportTicket, _a1 error) *MockTicketRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*store.SupportTicket, error)) *MockTicketRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function with given fields: ctx, ticketID
func (_m *MockTicketRepository) GetMessages(ctx context.Context, ticketID string) ([]store.TicketMessage, error) {
	ret := _m.Called(ctx, ticketID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []store.TicketMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]store.TicketMessage, error)); ok {
		return rf(ctx, ticketID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []store.TicketMessage); ok {
		r0 = rf(ctx, ticketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.TicketMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ticketID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockTicketRepository_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - ticketID string
func (_e *MockTicketRepository_Expecter) GetMessages(ctx interface{}, ticketID interface{}) *MockTicketRepository_GetMessages_Call {
	return &MockTicketRepository_GetMessages_Call{Call: _e.mock.On("GetMessages", ctx, ticketID)}
}

func (_c *MockTicketRepository_GetMessages_Call) Run(run func(ctx context.Context, ticketID string)) *MockTicketRepository_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTicketRepository_GetMessages_Call) Return(_a0 []store.TicketMessage, _a1 error) *MockTicketRepository_GetMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_GetMessages_Call) RunAndReturn(run func(context.Context, string) ([]store.TicketMessage, error)) *MockTicketRepository_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *MockTicketRepository) ListByUser(ctx context.Context, userID string) ([]store.SupportTicket, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []store.SupportTicket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]store.SupportTicket, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []store.SupportTicket); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.SupportTicket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTicketRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockTicketRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTicketRepository_Expecter) ListByUser(ctx interface{}, userID interface{}) *MockTicketRepository_ListByUser_Call {
	return &MockTicketRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", ctx, userID)}
}

func (_c *MockTicketRepository_ListByUser_Call) Run(run func(ctx context.Context, userID string)) *MockTicketRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTicketRepository_ListByUser_Call) Return(_a0 []store.SupportTicket, _a1 error) *MockTicketRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTicketRepository_ListByUser_Call) RunAndReturn(run func(context.Context, string) ([]store.SupportTicket, error)) *MockTicketRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTicketRepository creates a new instance of MockTicketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTicketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTicketRepository {
	mock := &MockTicketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
