// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	store "kronus.dev/commbadge_api/store"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// AddWarning provides a mock function with given fields: ctx, userID, adminID, reason
func (_m *MockUserRepository) AddWarning(ctx context.Context, userID string, adminID string, reason string) error {
	ret := _m.Called(ctx, userID, adminID, reason)

	if len(ret) == 0 {
		panic("no return value specified for AddWarning")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, userID, adminID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_AddWarning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWarning'
type MockUserRepository_AddWarning_Call struct {
	*mock.Call
}

// AddWarning is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - adminID string
//   - reason string
func (_e *MockUserRepository_Expecter) AddWarning(ctx interface{}, userID interface{}, adminID interface{}, reason interface{}) *MockUserRepository_AddWarning_Call {
	return &MockUserRepository_AddWarning_Call{Call: _e.mock.On("AddWarning", ctx, userID, adminID, reason)}
}

func (_c *MockUserRepository_AddWarning_Call) Run(run func(ctx context.Context, userID string, adminID string, reason string)) *MockUserRepository_AddWarning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockUserRepository_AddWarning_Call) Return(_a0 error) *MockUserRepository_AddWarning_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_AddWarning_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockUserRepository_AddWarning_Call {
	_c.Call.Return(run)
	return _c
}

// BanUser provides a mock function with given fields: ctx, userID, reason
func (_m *MockUserRepository) BanUser(ctx context.Context, userID string, reason string) error {
	ret := _m.Called(ctx, userID, reason)

	if len(ret) == 0 {
		panic("no return value specified for BanUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_BanUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BanUser'
type MockUserRepository_BanUser_Call struct {
	*mock.Call
}

// BanUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - reason string
func (_e *MockUserRepository_Expecter) BanUser(ctx interface{}, userID interface{}, reason interface{}) *MockUserRepository_BanUser_Call {
	return &MockUserRepository_BanUser_Call{Call: _e.mock.On("BanUser", ctx, userID, reason)}
}

func (_c *MockUserRepository_BanUser_Call) Run(run func(ctx context.Context, userID string, reason string)) *MockUserRepository_BanUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_BanUser_Call) Return(_a0 error) *MockUserRepository_BanUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_BanUser_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserRepository_BanUser_Call {
	_c.Call.Return(run)
	return _c
}

// ClearTwitchLink provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) ClearTwitchLink(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearTwitchLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_ClearTwitchLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearTwitchLink'
type MockUserRepository_ClearTwitchLink_Call struct {
	*mock.Call
}

// ClearTwitchLink is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) ClearTwitchLink(ctx interface{}, userID interface{}) *MockUserRepository_ClearTwitchLink_Call {
	return &MockUserRepository_ClearTwitchLink_Call{Call: _e.mock.On("ClearTwitchLink", ctx, userID)}
}

func (_c *MockUserRepository_ClearTwitchLink_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_ClearTwitchLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_ClearTwitchLink_Call) Return(_a0 error) *MockUserRepository_ClearTwitchLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_ClearTwitchLink_Call) RunAndReturn(run func(context.Context, string) error) *MockUserRepository_ClearTwitchLink_Call {
	_c.Call.Return(run)
	return _c
}

// GetTwitchID provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) GetTwitchID(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTwitchID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetTwitchID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTwitchID'
type MockUserRepository_GetTwitchID_Call struct {
	*mock.Call
}

// GetTwitchID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) GetTwitchID(ctx interface{}, userID interface{}) *MockUserRepository_GetTwitchID_Call {
	return &MockUserRepository_GetTwitchID_Call{Call: _e.mock.On("GetTwitchID", ctx, userID)}
}

func (_c *MockUserRepository_GetTwitchID_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_GetTwitchID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetTwitchID_Call) Return(_a0 string, _a1 error) *MockUserRepository_GetTwitchID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetTwitchID_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockUserRepository_GetTwitchID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockUserRepository) GetUserByID(ctx context.Context, id string) (*store.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *store.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*store.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *store.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockUserRepository_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUserRepository_GetUserByID_Call {
	return &MockUserRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserRepository_GetUserByID_Call) Run(run func(ctx context.Context, id string)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) Return(_a0 *store.User, _a1 error) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetUserByID_Call) RunAndReturn(run func(context.Context, string) (*store.User, error)) *MockUserRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetWarningLog provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) GetWarningLog(ctx context.Context, userID string) ([]store.UserWarning, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWarningLog")
	}

	var r0 []store.UserWarning
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]store.UserWarning, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []store.UserWarning); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.UserWarning)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetWarningLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWarningLog'
type MockUserRepository_GetWarningLog_Call struct {
	*mock.Call
}

// GetWarningLog is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) GetWarningLog(ctx interface{}, userID interface{}) *MockUserRepository_GetWarningLog_Call {
	return &MockUserRepository_GetWarningLog_Call{Call: _e.mock.On("GetWarningLog", ctx, userID)}
}

func (_c *MockUserRepository_GetWarningLog_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_GetWarningLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetWarningLog_Call) Return(_a0 []store.UserWarning, _a1 error) *MockUserRepository_GetWarningLog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetWarningLog_Call) RunAndReturn(run func(context.Context, string) ([]store.UserWarning, error)) *MockUserRepository_GetWarningLog_Call {
	_c.Call.Return(run)
	return _c
}

// IsBanned provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) IsBanned(ctx context.Context, userID string) (bool, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsBanned")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_IsBanned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsBanned'
type MockUserRepository_IsBanned_Call struct {
	*mock.Call
}

// IsBanned is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) IsBanned(ctx interface{}, userID interface{}) *MockUserRepository_IsBanned_Call {
	return &MockUserRepository_IsBanned_Call{Call: _e.mock.On("IsBanned", ctx, userID)}
}

func (_c *MockUserRepository_IsBanned_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_IsBanned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_IsBanned_Call) Return(_a0 bool, _a1 error) *MockUserRepository_IsBanned_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_IsBanned_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockUserRepository_IsBanned_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, limit, offset
func (_m *MockUserRepository) ListUsers(ctx context.Context, limit int, offset int) ([]store.UserAdminView, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []store.UserAdminView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]store.UserAdminView, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []store.UserAdminView); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.UserAdminView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUserRepository_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockUserRepository_Expecter) ListUsers(ctx interface{}, limit interface{}, offset interface{}) *MockUserRepository_ListUsers_Call {
	return &MockUserRepository_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, limit, offset)}
}

func (_c *MockUserRepository_ListUsers_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockUserRepository_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockUserRepository_ListUsers_Call) Return(_a0 []store.UserAdminView, _a1 error) *MockUserRepository_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_ListUsers_Call) RunAndReturn(run func(context.Context, int, int) ([]store.UserAdminView, error)) *MockUserRepository_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTwitchLink provides a mock function with given fields: ctx, userID, twitchID
func (_m *MockUserRepository) SaveTwitchLink(ctx context.Context, userID string, twitchID string) error {
	ret := _m.Called(ctx, userID, twitchID)

	if len(ret) == 0 {
		panic("no return value specified for SaveTwitchLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, twitchID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_SaveTwitchLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTwitchLink'
type MockUserRepository_SaveTwitchLink_Call struct {
	*mock.Call
}

// SaveTwitchLink is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - twitchID string
func (_e *MockUserRepository_Expecter) SaveTwitchLink(ctx interface{}, userID interface{}, twitchID interface{}) *MockUserRepository_SaveTwitchLink_Call {
	return &MockUserRepository_SaveTwitchLink_Call{Call: _e.mock.On("SaveTwitchLink", ctx, userID, twitchID)}
}

func (_c *MockUserRepository_SaveTwitchLink_Call) Run(run func(ctx context.Context, userID string, twitchID string)) *MockUserRepository_SaveTwitchLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_SaveTwitchLink_Call) Return(_a0 error) *MockUserRepository_SaveTwitchLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_SaveTwitchLink_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserRepository_SaveTwitchLink_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: ctx, query, limit
func (_m *MockUserRepository) SearchUsers(ctx context.Context, query string, limit int) ([]store.UserAdminView, error) {
	ret := _m.Called(ctx, query, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []store.UserAdminView
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]store.UserAdminView, error)); ok {
		return rf(ctx, query, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []store.UserAdminView); ok {
		r0 = rf(ctx, query, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.UserAdminView)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, query, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockUserRepository_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - limit int
func (_e *MockUserRepository_Expecter) SearchUsers(ctx interface{}, query interface{}, limit interface{}) *MockUserRepository_SearchUsers_Call {
	return &MockUserRepository_SearchUsers_Call{Call: _e.mock.On("SearchUsers", ctx, query, limit)}
}

func (_c *MockUserRepository_SearchUsers_Call) Run(run func(ctx context.Context, query string, limit int)) *MockUserRepository_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockUserRepository_SearchUsers_Call) Return(_a0 []store.UserAdminView, _a1 error) *MockUserRepository_SearchUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_SearchUsers_Call) RunAndReturn(run func(context.Context, string, int) ([]store.UserAdminView, error)) *MockUserRepository_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SetNotificationChannel provides a mock function with given fields: ctx, userID, channelID
func (_m *MockUserRepository) SetNotificationChannel(ctx context.Context, userID string, channelID string) error {
	ret := _m.Called(ctx, userID, channelID)

	if len(ret) == 0 {
		panic("no return value specified for SetNotificationChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, channelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_SetNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNotificationChannel'
type MockUserRepository_SetNotificationChannel_Call struct {
	*mock.Call
}

// SetNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - channelID string
func (_e *MockUserRepository_Expecter) SetNotificationChannel(ctx interface{}, userID interface{}, channelID interface{}) *MockUserRepository_SetNotificationChannel_Call {
	return &MockUserRepository_SetNotificationChannel_Call{Call: _e.mock.On("SetNotificationChannel", ctx, userID, channelID)}
}

func (_c *MockUserRepository_SetNotificationChannel_Call) Run(run func(ctx context.Context, userID string, channelID string)) *MockUserRepository_SetNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_SetNotificationChannel_Call) Return(_a0 error) *MockUserRepository_SetNotificationChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_SetNotificationChannel_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserRepository_SetNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}

// SetShoutoutTemplate provides a mock function with given fields: ctx, userID, template
func (_m *MockUserRepository) SetShoutoutTemplate(ctx context.Context, userID string, template string) error {
	ret := _m.Called(ctx, userID, template)

	if len(ret) == 0 {
		panic("no return value specified for SetShoutoutTemplate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, template)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_SetShoutoutTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetShoutoutTemplate'
type MockUserRepository_SetShoutoutTemplate_Call struct {
	*mock.Call
}

// SetShoutoutTemplate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - template string
func (_e *MockUserRepository_Expecter) SetShoutoutTemplate(ctx interface{}, userID interface{}, template interface{}) *MockUserRepository_SetShoutoutTemplate_Call {
	return &MockUserRepository_SetShoutoutTemplate_Call{Call: _e.mock.On("SetShoutoutTemplate", ctx, userID, template)}
}

func (_c *MockUserRepository_SetShoutoutTemplate_Call) Run(run func(ctx context.Context, userID string, template string)) *MockUserRepository_SetShoutoutTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_SetShoutoutTemplate_Call) Return(_a0 error) *MockUserRepository_SetShoutoutTemplate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_SetShoutoutTemplate_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserRepository_SetShoutoutTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// UnbanUser provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) UnbanUser(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnbanUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UnbanUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnbanUser'
type MockUserRepository_UnbanUser_Call struct {
	*mock.Call
}

// UnbanUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) UnbanUser(ctx interface{}, userID interface{}) *MockUserRepository_UnbanUser_Call {
	return &MockUserRepository_UnbanUser_Call{Call: _e.mock.On("UnbanUser", ctx, userID)}
}

func (_c *MockUserRepository_UnbanUser_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_UnbanUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_UnbanUser_Call) Return(_a0 error) *MockUserRepository_UnbanUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UnbanUser_Call) RunAndReturn(run func(context.Context, string) error) *MockUserRepository_UnbanUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUser provides a mock function with given fields: ctx, user
func (_m *MockUserRepository) UpsertUser(ctx context.Context, user *store.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *store.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUser'
type MockUserRepository_UpsertUser_Call struct {
	*mock.Call
}

// UpsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *store.User
func (_e *MockUserRepository_Expecter) UpsertUser(ctx interface{}, user interface{}) *MockUserRepository_UpsertUser_Call {
	return &MockUserRepository_UpsertUser_Call{Call: _e.mock.On("UpsertUser", ctx, user)}
}

func (_c *MockUserRepository_UpsertUser_Call) Run(run func(ctx context.Context, user *store.User)) *MockUserRepository_UpsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*store.User))
	})
	return _c
}

func (_c *MockUserRepository_UpsertUser_Call) Return(_a0 error) *MockUserRepository_UpsertUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpsertUser_Call) RunAndReturn(run func(context.Context, *store.User) error) *MockUserRepository_UpsertUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
