// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSessionPinger is an autogenerated mock type for the SessionPinger type
type MockSessionPinger struct {
	mock.Mock
}

type MockSessionPinger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionPinger) EXPECT() *MockSessionPinger_Expecter {
	return &MockSessionPinger_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function with given fields: ctx
func (_m *MockSessionPinger) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionPinger_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockSessionPinger_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSessionPinger_Expecter) Ping(ctx interface{}) *MockSessionPinger_Ping_Call {
	return &MockSessionPinger_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockSessionPinger_Ping_Call) Run(run func(ctx context.Context)) *MockSessionPinger_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSessionPinger_Ping_Call) Return(_a0 error) *MockSessionPinger_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionPinger_Ping_Call) RunAndReturn(run func(context.Context) error) *MockSessionPinger_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionPinger creates a new instance of MockSessionPinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionPinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionPinger {
	mock := &MockSessionPinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
