// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	store "kronus.dev/commbadge_api/store"
)

// MockCommunityRepository is an autogenerated mock type for the CommunityRepository type
type MockCommunityRepository struct {
	mock.Mock
}

type MockCommunityRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommunityRepository) EXPECT() *MockCommunityRepository_Expecter {
	return &MockCommunityRepository_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, communityID, userID, role
func (_m *MockCommunityRepository) AddMember(ctx context.Context, communityID string, userID string, role string) error {
	ret := _m.Called(ctx, communityID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, communityID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommunityRepository_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MockCommunityRepository_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - communityID string
//   - userID string
//   - role string
func (_e *MockCommunityRepository_Expecter) AddMember(ctx interface{}, communityID interface{}, userID interface{}, role interface{}) *MockCommunityRepository_AddMember_Call {
	return &MockCommunityRepository_AddMember_Call{Call: _e.mock.On("AddMember", ctx, communityID, userID, role)}
}

func (_c *MockCommunityRepository_AddMember_Call) Run(run func(ctx context.Context, communityID string, userID string, role string)) *MockCommunityRepository_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_AddMember_Call) Return(_a0 error) *MockCommunityRepository_AddMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommunityRepository_AddMember_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockCommunityRepository_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// AdminListAll provides a mock function with given fields: ctx, limit, offset
func (_m *MockCommunityRepository) AdminListAll(ctx context.Context, limit int, offset int) ([]store.Community, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for AdminListAll")
	}

	var r0 []store.Community
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]store.Community, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []store.Community); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.Community)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommunityRepository_AdminListAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminListAll'
type MockCommunityRepository_AdminListAll_Call struct {
	*mock.Call
}

// AdminListAll is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockCommunityRepository_Expecter) AdminListAll(ctx interface{}, limit interface{}, offset interface{}) *MockCommunityRepository_AdminListAll_Call {
	return &MockCommunityRepository_AdminListAll_Call{Call: _e.mock.On("AdminListAll", ctx, limit, offset)}
}

func (_c *MockCommunityRepository_AdminListAll_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockCommunityRepository_AdminListAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockCommunityRepository_AdminListAll_Call) Return(_a0 []store.Community, _a1 error) *MockCommunityRepository_AdminListAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommunityRepository_AdminListAll_Call) RunAndReturn(run func(context.Context, int, int) ([]store.Community, error)) *MockCommunityRepository_AdminListAll_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, name, description, ownerID
func (_m *MockCommunityRepository) Create(ctx context.Context, name string, description string, ownerID string) (*store.Community, error) {
	ret := _m.Called(ctx, name, description, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *store.Community
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*store.Community, error)); ok {
		return rf(ctx, name, description, ownerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *store.Community); ok {
		r0 = rf(ctx, name, description, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Community)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, name, description, ownerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommunityRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCommunityRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - description string
//   - ownerID string
func (_e *MockCommunityRepository_Expecter) Create(ctx interface{}, name interface{}, description interface{}, ownerID interface{}) *MockCommunityRepository_Create_Call {
	return &MockCommunityRepository_Create_Call{Call: _e.mock.On("Create", ctx, name, description, ownerID)}
}

func (_c *MockCommunityRepository_Create_Call) Run(run func(ctx context.Context, name string, description string, ownerID string)) *MockCommunityRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_Create_Call) Return(_a0 *store.Community, _a1 error) *MockCommunityRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommunityRepository_Create_Call) RunAndReturn(run func(context.Context, string, string, string) (*store.Community, error)) *MockCommunityRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockCommunityRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommunityRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCommunityRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCommunityRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockCommunityRepository_Delete_Call {
	return &MockCommunityRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockCommunityRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockCommunityRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_Delete_Call) Return(_a0 error) *MockCommunityRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommunityRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockCommunityRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockCommunityRepository) GetByID(ctx context.Context, id string) (*store.Community, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *store.Community
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*store.Community, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *store.Community); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Community)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommunityRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockCommunityRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCommunityRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockCommunityRepository_GetByID_Call {
	return &MockCommunityRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockCommunityRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockCommunityRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_GetByID_Call) Return(_a0 *store.Community, _a1 error) *MockCommunityRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommunityRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*store.Community, error)) *MockCommunityRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByJoinLinkID provides a mock function with given fields: ctx, joinLinkID
func (_m *MockCommunityRepository) GetByJoinLinkID(ctx context.Context, joinLinkID string) (*store.Community, error) {
	ret := _m.Called(ctx, joinLinkID)

	if len(ret) == 0 {
		panic("no return value specified for GetByJoinLinkID")
	}

	var r0 *store.Community
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*store.Community, error)); ok {
		return rf(ctx, joinLinkID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *store.Community); ok {
		r0 = rf(ctx, joinLinkID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.Community)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, joinLinkID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommunityRepository_GetByJoinLinkID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByJoinLinkID'
type MockCommunityRepository_GetByJoinLinkID_Call struct {
	*mock.Call
}

// GetByJoinLinkID is a helper method to define mock.On call
//   - ctx context.Context
//   - joinLinkID string
func (_e *MockCommunityRepository_Expecter) GetByJoinLinkID(ctx interface{}, joinLinkID interface{}) *MockCommunityRepository_GetByJoinLinkID_Call {
	return &MockCommunityRepository_GetByJoinLinkID_Call{Call: _e.mock.On("GetByJoinLinkID", ctx, joinLinkID)}
}

func (_c *MockCommunityRepository_GetByJoinLinkID_Call) Run(run func(ctx context.Context, joinLinkID string)) *MockCommunityRepository_GetByJoinLinkID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_GetByJoinLinkID_Call) Return(_a0 *store.Community, _a1 error) *MockCommunityRepository_GetByJoinLinkID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommunityRepository_GetByJoinLinkID_Call) RunAndReturn(run func(context.Context, string) (*store.Community, error)) *MockCommunityRepository_GetByJoinLinkID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberRole provides a mock function with given fields: ctx, communityID, userID
func (_m *MockCommunityRepository) GetMemberRole(ctx context.Context, communityID string, userID string) (string, error) {
	ret := _m.Called(ctx, communityID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberRole")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, communityID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, communityID, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, communityID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommunityRepository_GetMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberRole'
type MockCommunityRepository_GetMemberRole_Call struct {
	*mock.Call
}

// GetMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - communityID string
//   - userID string
func (_e *MockCommunityRepository_Expecter) GetMemberRole(ctx interface{}, communityID interface{}, userID interface{}) *MockCommunityRepository_GetMemberRole_Call {
	return &MockCommunityRepository_GetMemberRole_Call{Call: _e.mock.On("GetMemberRole", ctx, communityID, userID)}
}

func (_c *MockCommunityRepository_GetMemberRole_Call) Run(run func(ctx context.Context, communityID string, userID string)) *MockCommunityRepository_GetMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_GetMemberRole_Call) Return(_a0 string, _a1 error) *MockCommunityRepository_GetMemberRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommunityRepository_GetMemberRole_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *MockCommunityRepository_GetMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetMembers provides a mock function with given fields: ctx, communityID
func (_m *MockCommunityRepository) GetMembers(ctx context.Context, communityID string) ([]store.CommunityMember, error) {
	ret := _m.Called(ctx, communityID)

	if len(ret) == 0 {
		panic("no return value specified for GetMembers")
	}

	var r0 []store.CommunityMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]store.CommunityMember, error)); ok {
		return rf(ctx, communityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []store.CommunityMember); ok {
		r0 = rf(ctx, communityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.CommunityMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, communityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommunityRepository_GetMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMembers'
type MockCommunityRepository_GetMembers_Call struct {
	*mock.Call
}

// GetMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - communityID string
func (_e *MockCommunityRepository_Expecter) GetMembers(ctx interface{}, communityID interface{}) *MockCommunityRepository_GetMembers_Call {
	return &MockCommunityRepository_GetMembers_Call{Call: _e.mock.On("GetMembers", ctx, communityID)}
}

func (_c *MockCommunityRepository_GetMembers_Call) Run(run func(ctx context.Context, communityID string)) *MockCommunityRepository_GetMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_GetMembers_Call) Return(_a0 []store.CommunityMember, _a1 error) *MockCommunityRepository_GetMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommunityRepository_GetMembers_Call) RunAndReturn(run func(context.Context, string) ([]store.CommunityMember, error)) *MockCommunityRepository_GetMembers_Call {
	_c.Call.Return(run)
	return _c
}

// IsModeratorOrOwner provides a mock function with given fields: ctx, communityID, userID
func (_m *MockCommunityRepository) IsModeratorOrOwner(ctx context.Context, communityID string, userID string) (bool, error) {
	ret := _m.Called(ctx, communityID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsModeratorOrOwner")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, communityID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, communityID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, communityID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommunityRepository_IsModeratorOrOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsModeratorOrOwner'
type MockCommunityRepository_IsModeratorOrOwner_Call struct {
	*mock.Call
}

// IsModeratorOrOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - communityID string
//   - userID string
func (_e *MockCommunityRepository_Expecter) IsModeratorOrOwner(ctx interface{}, communityID interface{}, userID interface{}) *MockCommunityRepository_IsModeratorOrOwner_Call {
	return &MockCommunityRepository_IsModeratorOrOwner_Call{Call: _e.mock.On("IsModeratorOrOwner", ctx, communityID, userID)}
}

func (_c *MockCommunityRepository_IsModeratorOrOwner_Call) Run(run func(ctx context.Context, communityID string, userID string)) *MockCommunityRepository_IsModeratorOrOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_IsModeratorOrOwner_Call) Return(_a0 bool, _a1 error) *MockCommunityRepository_IsModeratorOrOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommunityRepository_IsModeratorOrOwner_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockCommunityRepository_IsModeratorOrOwner_Call {
	_c.Call.Return(run)
	return _c
}

// IsOwner provides a mock function with given fields: ctx, communityID, userID
func (_m *MockCommunityRepository) IsOwner(ctx context.Context, communityID string, userID string) (bool, error) {
	ret := _m.Called(ctx, communityID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsOwner")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, communityID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, communityID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, communityID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommunityRepository_IsOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsOwner'
type MockCommunityRepository_IsOwner_Call struct {
	*mock.Call
}

// IsOwner is a helper method to define mock.On call
//   - ctx context.Context
//   - communityID string
//   - userID string
func (_e *MockCommunityRepository_Expecter) IsOwner(ctx interface{}, communityID interface{}, userID interface{}) *MockCommunityRepository_IsOwner_Call {
	return &MockCommunityRepository_IsOwner_Call{Call: _e.mock.On("IsOwner", ctx, communityID, userID)}
}

func (_c *MockCommunityRepository_IsOwner_Call) Run(run func(ctx context.Context, communityID string, userID string)) *MockCommunityRepository_IsOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_IsOwner_Call) Return(_a0 bool, _a1 error) *MockCommunityRepository_IsOwner_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommunityRepository_IsOwner_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockCommunityRepository_IsOwner_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *MockCommunityRepository) ListByUserID(ctx context.Context, userID string) ([]store.CommunityWithRole, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []store.CommunityWithRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]store.CommunityWithRole, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []store.CommunityWithRole); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.CommunityWithRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommunityRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockCommunityRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockCommunityRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}) *MockCommunityRepository_ListByUserID_Call {
	return &MockCommunityRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockCommunityRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockCommunityRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_ListByUserID_Call) Return(_a0 []store.CommunityWithRole, _a1 error) *MockCommunityRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommunityRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, string) ([]store.CommunityWithRole, error)) *MockCommunityRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RegenerateJoinLink provides a mock function with given fields: ctx, id
func (_m *MockCommunityRepository) RegenerateJoinLink(ctx context.Context, id string) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RegenerateJoinLink")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommunityRepository_RegenerateJoinLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegenerateJoinLink'
type MockCommunityRepository_RegenerateJoinLink_Call struct {
	*mock.Call
}

// RegenerateJoinLink is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCommunityRepository_Expecter) RegenerateJoinLink(ctx interface{}, id interface{}) *MockCommunityRepository_RegenerateJoinLink_Call {
	return &MockCommunityRepository_RegenerateJoinLink_Call{Call: _e.mock.On("RegenerateJoinLink", ctx, id)}
}

func (_c *MockCommunityRepository_RegenerateJoinLink_Call) Run(run func(ctx context.Context, id string)) *MockCommunityRepository_RegenerateJoinLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_RegenerateJoinLink_Call) Return(_a0 string, _a1 error) *MockCommunityRepository_RegenerateJoinLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommunityRepository_RegenerateJoinLink_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockCommunityRepository_RegenerateJoinLink_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, communityID, userID
func (_m *MockCommunityRepository) RemoveMember(ctx context.Context, communityID string, userID string) error {
	ret := _m.Called(ctx, communityID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, communityID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommunityRepository_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockCommunityRepository_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - communityID string
//   - userID string
func (_e *MockCommunityRepository_Expecter) RemoveMember(ctx interface{}, communityID interface{}, userID interface{}) *MockCommunityRepository_RemoveMember_Call {
	return &MockCommunityRepository_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, communityID, userID)}
}

func (_c *MockCommunityRepository_RemoveMember_Call) Run(run func(ctx context.Context, communityID string, userID string)) *MockCommunityRepository_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_RemoveMember_Call) Return(_a0 error) *MockCommunityRepository_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommunityRepository_RemoveMember_Call) RunAndReturn(run func(context.Context, string, string) error) *MockCommunityRepository_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// SetDiscordConfig provides a mock function with given fields: ctx, id, guildID, liveChannelID
func (_m *MockCommunityRepository) SetDiscordConfig(ctx context.Context, id string, guildID string, liveChannelID string) error {
	ret := _m.Called(ctx, id, guildID, liveChannelID)

	if len(ret) == 0 {
		panic("no return value specified for SetDiscordConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, id, guildID, liveChannelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommunityRepository_SetDiscordConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDiscordConfig'
type MockCommunityRepository_SetDiscordConfig_Call struct {
	*mock.Call
}

// SetDiscordConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - guildID string
//   - liveChannelID string
func (_e *MockCommunityRepository_Expecter) SetDiscordConfig(ctx interface{}, id interface{}, guildID interface{}, liveChannelID interface{}) *MockCommunityRepository_SetDiscordConfig_Call {
	return &MockCommunityRepository_SetDiscordConfig_Call{Call: _e.mock.On("SetDiscordConfig", ctx, id, guildID, liveChannelID)}
}

func (_c *MockCommunityRepository_SetDiscordConfig_Call) Run(run func(ctx context.Context, id string, guildID string, liveChannelID string)) *MockCommunityRepository_SetDiscordConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_SetDiscordConfig_Call) Return(_a0 error) *MockCommunityRepository_SetDiscordConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommunityRepository_SetDiscordConfig_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockCommunityRepository_SetDiscordConfig_Call {
	_c.Call.Return(run)
	return _c
}

// TransferOwnership provides a mock function with given fields: ctx, communityID, newOwnerID
func (_m *MockCommunityRepository) TransferOwnership(ctx context.Context, communityID string, newOwnerID string) error {
	ret := _m.Called(ctx, communityID, newOwnerID)

	if len(ret) == 0 {
		panic("no return value specified for TransferOwnership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, communityID, newOwnerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommunityRepository_TransferOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferOwnership'
type MockCommunityRepository_TransferOwnership_Call struct {
	*mock.Call
}

// TransferOwnership is a helper method to define mock.On call
//   - ctx context.Context
//   - communityID string
//   - newOwnerID string
func (_e *MockCommunityRepository_Expecter) TransferOwnership(ctx interface{}, communityID interface{}, newOwnerID interface{}) *MockCommunityRepository_TransferOwnership_Call {
	return &MockCommunityRepository_TransferOwnership_Call{Call: _e.mock.On("TransferOwnership", ctx, communityID, newOwnerID)}
}

func (_c *MockCommunityRepository_TransferOwnership_Call) Run(run func(ctx context.Context, communityID string, newOwnerID string)) *MockCommunityRepository_TransferOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_TransferOwnership_Call) Return(_a0 error) *MockCommunityRepository_TransferOwnership_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommunityRepository_TransferOwnership_Call) RunAndReturn(run func(context.Context, string, string) error) *MockCommunityRepository_TransferOwnership_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, name, description
func (_m *MockCommunityRepository) Update(ctx context.Context, id string, name string, description string) error {
	ret := _m.Called(ctx, id, name, description)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, id, name, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommunityRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCommunityRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - name string
//   - description string
func (_e *MockCommunityRepository_Expecter) Update(ctx interface{}, id interface{}, name interface{}, description interface{}) *MockCommunityRepository_Update_Call {
	return &MockCommunityRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, name, description)}
}

func (_c *MockCommunityRepository_Update_Call) Run(run func(ctx context.Context, id string, name string, description string)) *MockCommunityRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_Update_Call) Return(_a0 error) *MockCommunityRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommunityRepository_Update_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockCommunityRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJoinLinkSettings provides a mock function with given fields: ctx, id, rotateOnRemoval, rotateOnLeave
func (_m *MockCommunityRepository) UpdateJoinLinkSettings(ctx context.Context, id string, rotateOnRemoval bool, rotateOnLeave bool) error {
	ret := _m.Called(ctx, id, rotateOnRemoval, rotateOnLeave)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJoinLinkSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, bool) error); ok {
		r0 = rf(ctx, id, rotateOnRemoval, rotateOnLeave)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommunityRepository_UpdateJoinLinkSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJoinLinkSettings'
type MockCommunityRepository_UpdateJoinLinkSettings_Call struct {
	*mock.Call
}

// UpdateJoinLinkSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - rotateOnRemoval bool
//   - rotateOnLeave bool
func (_e *MockCommunityRepository_Expecter) UpdateJoinLinkSettings(ctx interface{}, id interface{}, rotateOnRemoval interface{}, rotateOnLeave interface{}) *MockCommunityRepository_UpdateJoinLinkSettings_Call {
	return &MockCommunityRepository_UpdateJoinLinkSettings_Call{Call: _e.mock.On("UpdateJoinLinkSettings", ctx, id, rotateOnRemoval, rotateOnLeave)}
}

func (_c *MockCommunityRepository_UpdateJoinLinkSettings_Call) Run(run func(ctx context.Context, id string, rotateOnRemoval bool, rotateOnLeave bool)) *MockCommunityRepository_UpdateJoinLinkSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool), args[3].(bool))
	})
	return _c
}

func (_c *MockCommunityRepository_UpdateJoinLinkSettings_Call) Return(_a0 error) *MockCommunityRepository_UpdateJoinLinkSettings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommunityRepository_UpdateJoinLinkSettings_Call) RunAndReturn(run func(context.Context, string, bool, bool) error) *MockCommunityRepository_UpdateJoinLinkSettings_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLogoURL provides a mock function with given fields: ctx, id, url
func (_m *MockCommunityRepository) UpdateLogoURL(ctx context.Context, id string, url string) error {
	ret := _m.Called(ctx, id, url)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLogoURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommunityRepository_UpdateLogoURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLogoURL'
type MockCommunityRepository_UpdateLogoURL_Call struct {
	*mock.Call
}

// UpdateLogoURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - url string
func (_e *MockCommunityRepository_Expecter) UpdateLogoURL(ctx interface{}, id interface{}, url interface{}) *MockCommunityRepository_UpdateLogoURL_Call {
	return &MockCommunityRepository_UpdateLogoURL_Call{Call: _e.mock.On("UpdateLogoURL", ctx, id, url)}
}

func (_c *MockCommunityRepository_UpdateLogoURL_Call) Run(run func(ctx context.Context, id string, url string)) *MockCommunityRepository_UpdateLogoURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCommunityRepository_UpdateLogoURL_Call) Return(_a0 error) *MockCommunityRepository_UpdateLogoURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommunityRepository_UpdateLogoURL_Call) RunAndReturn(run func(context.Context, string, string) error) *MockCommunityRepository_UpdateLogoURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommunityRepository creates a new instance of MockCommunityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommunityRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommunityRepository {
	mock := &MockCommunityRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
