// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	session "kronus.dev/commbadge_api/session"

	time "time"
)

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockSessionStore) Create(ctx context.Context, _a1 *session.Session) (string, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *session.Session) (string, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *session.Session) string); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *session.Session) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *session.Session
func (_e *MockSessionStore_Expecter) Create(ctx interface{}, _a1 interface{}) *MockSessionStore_Create_Call {
	return &MockSessionStore_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockSessionStore_Create_Call) Run(run func(ctx context.Context, _a1 *session.Session)) *MockSessionStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*session.Session))
	})
	return _c
}

func (_c *MockSessionStore_Create_Call) Return(_a0 string, _a1 error) *MockSessionStore_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_Create_Call) RunAndReturn(run func(context.Context, *session.Session) (string, error)) *MockSessionStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, sessionID
func (_m *MockSessionStore) Delete(ctx context.Context, sessionID string) error {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionStore_Expecter) Delete(ctx interface{}, sessionID interface{}) *MockSessionStore_Delete_Call {
	return &MockSessionStore_Delete_Call{Call: _e.mock.On("Delete", ctx, sessionID)}
}

func (_c *MockSessionStore_Delete_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionStore_Delete_Call) Return(_a0 error) *MockSessionStore_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockSessionStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, sessionID
func (_m *MockSessionStore) Get(ctx context.Context, sessionID string) (*session.Session, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *session.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*session.Session, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *session.Session); ok {
		r0 = rf(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
func (_e *MockSessionStore_Expecter) Get(ctx interface{}, sessionID interface{}) *MockSessionStore_Get_Call {
	return &MockSessionStore_Get_Call{Call: _e.mock.On("Get", ctx, sessionID)}
}

func (_c *MockSessionStore_Get_Call) Run(run func(ctx context.Context, sessionID string)) *MockSessionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionStore_Get_Call) Return(_a0 *session.Session, _a1 error) *MockSessionStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_Get_Call) RunAndReturn(run func(context.Context, string) (*session.Session, error)) *MockSessionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// SetState provides a mock function with given fields: ctx, state, binding, ttl
func (_m *MockSessionStore) SetState(ctx context.Context, state string, binding string, ttl time.Duration) error {
	ret := _m.Called(ctx, state, binding, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = rf(ctx, state, binding, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_SetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetState'
type MockSessionStore_SetState_Call struct {
	*mock.Call
}

// SetState is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
//   - binding string
//   - ttl time.Duration
func (_e *MockSessionStore_Expecter) SetState(ctx interface{}, state interface{}, binding interface{}, ttl interface{}) *MockSessionStore_SetState_Call {
	return &MockSessionStore_SetState_Call{Call: _e.mock.On("SetState", ctx, state, binding, ttl)}
}

func (_c *MockSessionStore_SetState_Call) Run(run func(ctx context.Context, state string, binding string, ttl time.Duration)) *MockSessionStore_SetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockSessionStore_SetState_Call) Return(_a0 error) *MockSessionStore_SetState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_SetState_Call) RunAndReturn(run func(context.Context, string, string, time.Duration) error) *MockSessionStore_SetState_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyState provides a mock function with given fields: ctx, state
func (_m *MockSessionStore) VerifyState(ctx context.Context, state string) (string, bool, error) {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for VerifyState")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, bool, error)); ok {
		return rf(ctx, state)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = rf(ctx, state)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, state)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSessionStore_VerifyState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyState'
type MockSessionStore_VerifyState_Call struct {
	*mock.Call
}

// VerifyState is a helper method to define mock.On call
//   - ctx context.Context
//   - state string
func (_e *MockSessionStore_Expecter) VerifyState(ctx interface{}, state interface{}) *MockSessionStore_VerifyState_Call {
	return &MockSessionStore_VerifyState_Call{Call: _e.mock.On("VerifyState", ctx, state)}
}

func (_c *MockSessionStore_VerifyState_Call) Run(run func(ctx context.Context, state string)) *MockSessionStore_VerifyState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSessionStore_VerifyState_Call) Return(_a0 string, _a1 bool, _a2 error) *MockSessionStore_VerifyState_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSessionStore_VerifyState_Call) RunAndReturn(run func(context.Context, string) (string, bool, error)) *MockSessionStore_VerifyState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
