// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	twitch "kronus.dev/commbadge_api/twitch"
)

// MockTwitchClient is an autogenerated mock type for the TwitchClient type
type MockTwitchClient struct {
	mock.Mock
}

type MockTwitchClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTwitchClient) EXPECT() *MockTwitchClient_Expecter {
	return &MockTwitchClient_Expecter{mock: &_m.Mock}
}

// AuthURL provides a mock function with given fields: state, codeChallenge
func (_m *MockTwitchClient) AuthURL(state string, codeChallenge string) string {
	ret := _m.Called(state, codeChallenge)

	if len(ret) == 0 {
		panic("no return value specified for AuthURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(state, codeChallenge)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTwitchClient_AuthURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthURL'
type MockTwitchClient_AuthURL_Call struct {
	*mock.Call
}

// AuthURL is a helper method to define mock.On call
//   - state string
//   - codeChallenge string
func (_e *MockTwitchClient_Expecter) AuthURL(state interface{}, codeChallenge interface{}) *MockTwitchClient_AuthURL_Call {
	return &MockTwitchClient_AuthURL_Call{Call: _e.mock.On("AuthURL", state, codeChallenge)}
}

func (_c *MockTwitchClient_AuthURL_Call) Run(run func(state string, codeChallenge string)) *MockTwitchClient_AuthURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockTwitchClient_AuthURL_Call) Return(_a0 string) *MockTwitchClient_AuthURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTwitchClient_AuthURL_Call) RunAndReturn(run func(string, string) string) *MockTwitchClient_AuthURL_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function with given fields: ctx, code, verifier
func (_m *MockTwitchClient) Exchange(ctx context.Context, code string, verifier string) (*twitch.TokenResponse, error) {
	ret := _m.Called(ctx, code, verifier)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 *twitch.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*twitch.TokenResponse, error)); ok {
		return rf(ctx, code, verifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *twitch.TokenResponse); ok {
		r0 = rf(ctx, code, verifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*twitch.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, code, verifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTwitchClient_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type MockTwitchClient_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - verifier string
func (_e *MockTwitchClient_Expecter) Exchange(ctx interface{}, code interface{}, verifier interface{}) *MockTwitchClient_Exchange_Call {
	return &MockTwitchClient_Exchange_Call{Call: _e.mock.On("Exchange", ctx, code, verifier)}
}

func (_c *MockTwitchClient_Exchange_Call) Run(run func(ctx context.Context, code string, verifier string)) *MockTwitchClient_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTwitchClient_Exchange_Call) Return(_a0 *twitch.TokenResponse, _a1 error) *MockTwitchClient_Exchange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTwitchClient_Exchange_Call) RunAndReturn(run func(context.Context, string, string) (*twitch.TokenResponse, error)) *MockTwitchClient_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, accessToken
func (_m *MockTwitchClient) GetUser(ctx context.Context, accessToken string) (*twitch.TwitchUser, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *twitch.TwitchUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*twitch.TwitchUser, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *twitch.TwitchUser); ok {
		r0 = rf(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*twitch.TwitchUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTwitchClient_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockTwitchClient_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockTwitchClient_Expecter) GetUser(ctx interface{}, accessToken interface{}) *MockTwitchClient_GetUser_Call {
	return &MockTwitchClient_GetUser_Call{Call: _e.mock.On("GetUser", ctx, accessToken)}
}

func (_c *MockTwitchClient_GetUser_Call) Run(run func(ctx context.Context, accessToken string)) *MockTwitchClient_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTwitchClient_GetUser_Call) Return(_a0 *twitch.TwitchUser, _a1 error) *MockTwitchClient_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTwitchClient_GetUser_Call) RunAndReturn(run func(context.Context, string) (*twitch.TwitchUser, error)) *MockTwitchClient_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyIDToken provides a mock function with given fields: ctx, idToken, nonce
func (_m *MockTwitchClient) VerifyIDToken(ctx context.Context, idToken string, nonce string) error {
	ret := _m.Called(ctx, idToken, nonce)

	if len(ret) == 0 {
		panic("no return value specified for VerifyIDToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, idToken, nonce)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTwitchClient_VerifyIDToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyIDToken'
type MockTwitchClient_VerifyIDToken_Call struct {
	*mock.Call
}

// VerifyIDToken is a helper method to define mock.On call
//   - ctx context.Context
//   - idToken string
//   - nonce string
func (_e *MockTwitchClient_Expecter) VerifyIDToken(ctx interface{}, idToken interface{}, nonce interface{}) *MockTwitchClient_VerifyIDToken_Call {
	return &MockTwitchClient_VerifyIDToken_Call{Call: _e.mock.On("VerifyIDToken", ctx, idToken, nonce)}
}

func (_c *MockTwitchClient_VerifyIDToken_Call) Run(run func(ctx context.Context, idToken string, nonce string)) *MockTwitchClient_VerifyIDToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTwitchClient_VerifyIDToken_Call) Return(_a0 error) *MockTwitchClient_VerifyIDToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTwitchClient_VerifyIDToken_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTwitchClient_VerifyIDToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTwitchClient creates a new instance of MockTwitchClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTwitchClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTwitchClient {
	mock := &MockTwitchClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
