// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	twitch "kronus.dev/commbadge_api/twitch"
)

// MockTwitchEventSubClient is an autogenerated mock type for the TwitchEventSubClient type
type MockTwitchEventSubClient struct {
	mock.Mock
}

type MockTwitchEventSubClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTwitchEventSubClient) EXPECT() *MockTwitchEventSubClient_Expecter {
	return &MockTwitchEventSubClient_Expecter{mock: &_m.Mock}
}

// CreateSubscription provides a mock function with given fields: ctx, appToken, eventType, version, condition, callback, secret
func (_m *MockTwitchEventSubClient) CreateSubscription(ctx context.Context, appToken string, eventType string, version string, condition map[string]string, callback string, secret string) (*twitch.EventSubSubscription, error) {
	ret := _m.Called(ctx, appToken, eventType, version, condition, callback, secret)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubscription")
	}

	var r0 *twitch.EventSubSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]string, string, string) (*twitch.EventSubSubscription, error)); ok {
		return rf(ctx, appToken, eventType, version, condition, callback, secret)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]string, string, string) *twitch.EventSubSubscription); ok {
		r0 = rf(ctx, appToken, eventType, version, condition, callback, secret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*twitch.EventSubSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, map[string]string, string, string) error); ok {
		r1 = rf(ctx, appToken, eventType, version, condition, callback, secret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTwitchEventSubClient_CreateSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubscription'
type MockTwitchEventSubClient_CreateSubscription_Call struct {
	*mock.Call
}

// CreateSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - appToken string
//   - eventType string
//   - version string
//   - condition map[string]string
//   - callback string
//   - secret string
func (_e *MockTwitchEventSubClient_Expecter) CreateSubscription(ctx interface{}, appToken interface{}, eventType interface{}, version interface{}, condition interface{}, callback interface{}, secret interface{}) *MockTwitchEventSubClient_CreateSubscription_Call {
	return &MockTwitchEventSubClient_CreateSubscription_Call{Call: _e.mock.On("CreateSubscription", ctx, appToken, eventType, version, condition, callback, secret)}
}

func (_c *MockTwitchEventSubClient_CreateSubscription_Call) Run(run func(ctx context.Context, appToken string, eventType string, version string, condition map[string]string, callback string, secret string)) *MockTwitchEventSubClient_CreateSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(map[string]string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *MockTwitchEventSubClient_CreateSubscription_Call) Return(_a0 *twitch.EventSubSubscription, _a1 error) *MockTwitchEventSubClient_CreateSubscription_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTwitchEventSubClient_CreateSubscription_Call) RunAndReturn(run func(context.Context, string, string, string, map[string]string, string, string) (*twitch.EventSubSubscription, error)) *MockTwitchEventSubClient_CreateSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSubscription provides a mock function with given fields: ctx, appToken, id
func (_m *MockTwitchEventSubClient) DeleteSubscription(ctx context.Context, appToken string, id string) error {
	ret := _m.Called(ctx, appToken, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, appToken, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTwitchEventSubClient_DeleteSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubscription'
type MockTwitchEventSubClient_DeleteSubscription_Call struct {
	*mock.Call
}

// DeleteSubscription is a helper method to define mock.On call
//   - ctx context.Context
//   - appToken string
//   - id string
func (_e *MockTwitchEventSubClient_Expecter) DeleteSubscription(ctx interface{}, appToken interface{}, id interface{}) *MockTwitchEventSubClient_DeleteSubscription_Call {
	return &MockTwitchEventSubClient_DeleteSubscription_Call{Call: _e.mock.On("DeleteSubscription", ctx, appToken, id)}
}

func (_c *MockTwitchEventSubClient_DeleteSubscription_Call) Run(run func(ctx context.Context, appToken string, id string)) *MockTwitchEventSubClient_DeleteSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTwitchEventSubClient_DeleteSubscription_Call) Return(_a0 error) *MockTwitchEventSubClient_DeleteSubscription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTwitchEventSubClient_DeleteSubscription_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTwitchEventSubClient_DeleteSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppAccessToken provides a mock function with given fields: ctx
func (_m *MockTwitchEventSubClient) GetAppAccessToken(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAppAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTwitchEventSubClient_GetAppAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppAccessToken'
type MockTwitchEventSubClient_GetAppAccessToken_Call struct {
	*mock.Call
}

// GetAppAccessToken is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTwitchEventSubClient_Expecter) GetAppAccessToken(ctx interface{}) *MockTwitchEventSubClient_GetAppAccessToken_Call {
	return &MockTwitchEventSubClient_GetAppAccessToken_Call{Call: _e.mock.On("GetAppAccessToken", ctx)}
}

func (_c *MockTwitchEventSubClient_GetAppAccessToken_Call) Run(run func(ctx context.Context)) *MockTwitchEventSubClient_GetAppAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTwitchEventSubClient_GetAppAccessToken_Call) Return(_a0 string, _a1 error) *MockTwitchEventSubClient_GetAppAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTwitchEventSubClient_GetAppAccessToken_Call) RunAndReturn(run func(context.Context) (string, error)) *MockTwitchEventSubClient_GetAppAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTwitchEventSubClient creates a new instance of MockTwitchEventSubClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTwitchEventSubClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTwitchEventSubClient {
	mock := &MockTwitchEventSubClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
