// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAdminRepository is an autogenerated mock type for the AdminRepository type
type MockAdminRepository struct {
	mock.Mock
}

type MockAdminRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminRepository) EXPECT() *MockAdminRepository_Expecter {
	return &MockAdminRepository_Expecter{mock: &_m.Mock}
}

// IsAdmin provides a mock function with given fields: ctx, userID
func (_m *MockAdminRepository) IsAdmin(ctx context.Context, userID string) (bool, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsAdmin")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminRepository_IsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAdmin'
type MockAdminRepository_IsAdmin_Call struct {
	*mock.Call
}

// IsAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAdminRepository_Expecter) IsAdmin(ctx interface{}, userID interface{}) *MockAdminRepository_IsAdmin_Call {
	return &MockAdminRepository_IsAdmin_Call{Call: _e.mock.On("IsAdmin", ctx, userID)}
}

func (_c *MockAdminRepository_IsAdmin_Call) Run(run func(ctx context.Context, userID string)) *MockAdminRepository_IsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAdminRepository_IsAdmin_Call) Return(_a0 bool, _a1 error) *MockAdminRepository_IsAdmin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminRepository_IsAdmin_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockAdminRepository_IsAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminRepository creates a new instance of MockAdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminRepository {
	mock := &MockAdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
