// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	discord "kronus.dev/commbadge_api/discord"

	mock "github.com/stretchr/testify/mock"
)

// MockDiscordClient is an autogenerated mock type for the DiscordClient type
type MockDiscordClient struct {
	mock.Mock
}

type MockDiscordClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDiscordClient) EXPECT() *MockDiscordClient_Expecter {
	return &MockDiscordClient_Expecter{mock: &_m.Mock}
}

// AuthURL provides a mock function with given fields: state, codeChallenge
func (_m *MockDiscordClient) AuthURL(state string, codeChallenge string) string {
	ret := _m.Called(state, codeChallenge)

	if len(ret) == 0 {
		panic("no return value specified for AuthURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(state, codeChallenge)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDiscordClient_AuthURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthURL'
type MockDiscordClient_AuthURL_Call struct {
	*mock.Call
}

// AuthURL is a helper method to define mock.On call
//   - state string
//   - codeChallenge string
func (_e *MockDiscordClient_Expecter) AuthURL(state interface{}, codeChallenge interface{}) *MockDiscordClient_AuthURL_Call {
	return &MockDiscordClient_AuthURL_Call{Call: _e.mock.On("AuthURL", state, codeChallenge)}
}

func (_c *MockDiscordClient_AuthURL_Call) Run(run func(state string, codeChallenge string)) *MockDiscordClient_AuthURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockDiscordClient_AuthURL_Call) Return(_a0 string) *MockDiscordClient_AuthURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDiscordClient_AuthURL_Call) RunAndReturn(run func(string, string) string) *MockDiscordClient_AuthURL_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function with given fields: ctx, code, verifier
func (_m *MockDiscordClient) Exchange(ctx context.Context, code string, verifier string) (*discord.TokenResponse, error) {
	ret := _m.Called(ctx, code, verifier)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 *discord.TokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*discord.TokenResponse, error)); ok {
		return rf(ctx, code, verifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *discord.TokenResponse); ok {
		r0 = rf(ctx, code, verifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*discord.TokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, code, verifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDiscordClient_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type MockDiscordClient_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - verifier string
func (_e *MockDiscordClient_Expecter) Exchange(ctx interface{}, code interface{}, verifier interface{}) *MockDiscordClient_Exchange_Call {
	return &MockDiscordClient_Exchange_Call{Call: _e.mock.On("Exchange", ctx, code, verifier)}
}

func (_c *MockDiscordClient_Exchange_Call) Run(run func(ctx context.Context, code string, verifier string)) *MockDiscordClient_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDiscordClient_Exchange_Call) Return(_a0 *discord.TokenResponse, _a1 error) *MockDiscordClient_Exchange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDiscordClient_Exchange_Call) RunAndReturn(run func(context.Context, string, string) (*discord.TokenResponse, error)) *MockDiscordClient_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// GetChannel provides a mock function with given fields: ctx, botToken, channelID
func (_m *MockDiscordClient) GetChannel(ctx context.Context, botToken string, channelID string) (*discord.Channel, error) {
	ret := _m.Called(ctx, botToken, channelID)

	if len(ret) == 0 {
		panic("no return value specified for GetChannel")
	}

	var r0 *discord.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*discord.Channel, error)); ok {
		return rf(ctx, botToken, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *discord.Channel); ok {
		r0 = rf(ctx, botToken, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*discord.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, botToken, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDiscordClient_GetChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannel'
type MockDiscordClient_GetChannel_Call struct {
	*mock.Call
}

// GetChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - botToken string
//   - channelID string
func (_e *MockDiscordClient_Expecter) GetChannel(ctx interface{}, botToken interface{}, channelID interface{}) *MockDiscordClient_GetChannel_Call {
	return &MockDiscordClient_GetChannel_Call{Call: _e.mock.On("GetChannel", ctx, botToken, channelID)}
}

func (_c *MockDiscordClient_GetChannel_Call) Run(run func(ctx context.Context, botToken string, channelID string)) *MockDiscordClient_GetChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDiscordClient_GetChannel_Call) Return(_a0 *discord.Channel, _a1 error) *MockDiscordClient_GetChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDiscordClient_GetChannel_Call) RunAndReturn(run func(context.Context, string, string) (*discord.Channel, error)) *MockDiscordClient_GetChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, accessToken
func (_m *MockDiscordClient) GetUser(ctx context.Context, accessToken string) (*discord.User, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *discord.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*discord.User, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *discord.User); ok {
		r0 = rf(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*discord.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDiscordClient_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockDiscordClient_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockDiscordClient_Expecter) GetUser(ctx interface{}, accessToken interface{}) *MockDiscordClient_GetUser_Call {
	return &MockDiscordClient_GetUser_Call{Call: _e.mock.On("GetUser", ctx, accessToken)}
}

func (_c *MockDiscordClient_GetUser_Call) Run(run func(ctx context.Context, accessToken string)) *MockDiscordClient_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDiscordClient_GetUser_Call) Return(_a0 *discord.User, _a1 error) *MockDiscordClient_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDiscordClient_GetUser_Call) RunAndReturn(run func(context.Context, string) (*discord.User, error)) *MockDiscordClient_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserGuilds provides a mock function with given fields: ctx, accessToken
func (_m *MockDiscordClient) GetUserGuilds(ctx context.Context, accessToken string) ([]discord.Guild, error) {
	ret := _m.Called(ctx, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetUserGuilds")
	}

	var r0 []discord.Guild
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]discord.Guild, error)); ok {
		return rf(ctx, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []discord.Guild); ok {
		r0 = rf(ctx, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]discord.Guild)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDiscordClient_GetUserGuilds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserGuilds'
type MockDiscordClient_GetUserGuilds_Call struct {
	*mock.Call
}

// GetUserGuilds is a helper method to define mock.On call
//   - ctx context.Context
//   - accessToken string
func (_e *MockDiscordClient_Expecter) GetUserGuilds(ctx interface{}, accessToken interface{}) *MockDiscordClient_GetUserGuilds_Call {
	return &MockDiscordClient_GetUserGuilds_Call{Call: _e.mock.On("GetUserGuilds", ctx, accessToken)}
}

func (_c *MockDiscordClient_GetUserGuilds_Call) Run(run func(ctx context.Context, accessToken string)) *MockDiscordClient_GetUserGuilds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDiscordClient_GetUserGuilds_Call) Return(_a0 []discord.Guild, _a1 error) *MockDiscordClient_GetUserGuilds_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDiscordClient_GetUserGuilds_Call) RunAndReturn(run func(context.Context, string) ([]discord.Guild, error)) *MockDiscordClient_GetUserGuilds_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDiscordClient creates a new instance of MockDiscordClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDiscordClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDiscordClient {
	mock := &MockDiscordClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
