// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	store "kronus.dev/commbadge_api/store"
)

// MockSubscriptionRepository is an autogenerated mock type for the SubscriptionRepository type
type MockSubscriptionRepository struct {
	mock.Mock
}

type MockSubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepository_Expecter {
	return &MockSubscriptionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, userID, eventType, condition, twitchSubscriptionID
func (_m *MockSubscriptionRepository) Create(ctx context.Context, userID string, eventType string, condition map[string]string, twitchSubscriptionID string) (*store.NotificationSubscription, error) {
	ret := _m.Called(ctx, userID, eventType, condition, twitchSubscriptionID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *store.NotificationSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]string, string) (*store.NotificationSubscription, error)); ok {
		return rf(ctx, userID, eventType, condition, twitchSubscriptionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]string, string) *store.NotificationSubscription); ok {
		r0 = rf(ctx, userID, eventType, condition, twitchSubscriptionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.NotificationSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, map[string]string, string) error); ok {
		r1 = rf(ctx, userID, eventType, condition, twitchSubscriptionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSubscriptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - eventType string
//   - condition map[string]string
//   - twitchSubscriptionID string
func (_e *MockSubscriptionRepository_Expecter) Create(ctx interface{}, userID interface{}, eventType interface{}, condition interface{}, twitchSubscriptionID interface{}) *MockSubscriptionRepository_Create_Call {
	return &MockSubscriptionRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, eventType, condition, twitchSubscriptionID)}
}

func (_c *MockSubscriptionRepository_Create_Call) Run(run func(ctx context.Context, userID string, eventType string, condition map[string]string, twitchSubscriptionID string)) *MockSubscriptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]string), args[4].(string))
	})
	return _c
}

func (_c *MockSubscriptionRepository_Create_Call) Return(_a0 *store.NotificationSubscription, _a1 error) *MockSubscriptionRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_Create_Call) RunAndReturn(run func(context.Context, string, string, map[string]string, string) (*store.NotificationSubscription, error)) *MockSubscriptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockSubscriptionRepository) GetByID(ctx context.Context, id string) (*store.NotificationSubscription, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *store.NotificationSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*store.NotificationSubscription, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *store.NotificationSubscription); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*store.NotificationSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSubscriptionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSubscriptionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockSubscriptionRepository_GetByID_Call {
	return &MockSubscriptionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSubscriptionRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSubscriptionRepository_GetByID_Call) Return(_a0 *store.NotificationSubscription, _a1 error) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*store.NotificationSubscription, error)) *MockSubscriptionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// HasActive provides a mock function with given fields: ctx, userID, eventType
func (_m *MockSubscriptionRepository) HasActive(ctx context.Context, userID string, eventType string) (bool, error) {
	ret := _m.Called(ctx, userID, eventType)

	if len(ret) == 0 {
		panic("no return value specified for HasActive")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, userID, eventType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userID, eventType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, eventType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_HasActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasActive'
type MockSubscriptionRepository_HasActive_Call struct {
	*mock.Call
}

// HasActive is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - eventType string
func (_e *MockSubscriptionRepository_Expecter) HasActive(ctx interface{}, userID interface{}, eventType interface{}) *MockSubscriptionRepository_HasActive_Call {
	return &MockSubscriptionRepository_HasActive_Call{Call: _e.mock.On("HasActive", ctx, userID, eventType)}
}

func (_c *MockSubscriptionRepository_HasActive_Call) Run(run func(ctx context.Context, userID string, eventType string)) *MockSubscriptionRepository_HasActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSubscriptionRepository_HasActive_Call) Return(_a0 bool, _a1 error) *MockSubscriptionRepository_HasActive_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_HasActive_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *MockSubscriptionRepository_HasActive_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveByUser provides a mock function with given fields: ctx, userID
func (_m *MockSubscriptionRepository) ListActiveByUser(ctx context.Context, userID string) ([]store.NotificationSubscription, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveByUser")
	}

	var r0 []store.NotificationSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]store.NotificationSubscription, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []store.NotificationSubscription); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.NotificationSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_ListActiveByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveByUser'
type MockSubscriptionRepository_ListActiveByUser_Call struct {
	*mock.Call
}

// ListActiveByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockSubscriptionRepository_Expecter) ListActiveByUser(ctx interface{}, userID interface{}) *MockSubscriptionRepository_ListActiveByUser_Call {
	return &MockSubscriptionRepository_ListActiveByUser_Call{Call: _e.mock.On("ListActiveByUser", ctx, userID)}
}

func (_c *MockSubscriptionRepository_ListActiveByUser_Call) Run(run func(ctx context.Context, userID string)) *MockSubscriptionRepository_ListActiveByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSubscriptionRepository_ListActiveByUser_Call) Return(_a0 []store.NotificationSubscription, _a1 error) *MockSubscriptionRepository_ListActiveByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_ListActiveByUser_Call) RunAndReturn(run func(context.Context, string) ([]store.NotificationSubscription, error)) *MockSubscriptionRepository_ListActiveByUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRevoked provides a mock function with given fields: ctx, id
func (_m *MockSubscriptionRepository) MarkRevoked(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkRevoked")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscriptionRepository_MarkRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRevoked'
type MockSubscriptionRepository_MarkRevoked_Call struct {
	*mock.Call
}

// MarkRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSubscriptionRepository_Expecter) MarkRevoked(ctx interface{}, id interface{}) *MockSubscriptionRepository_MarkRevoked_Call {
	return &MockSubscriptionRepository_MarkRevoked_Call{Call: _e.mock.On("MarkRevoked", ctx, id)}
}

func (_c *MockSubscriptionRepository_MarkRevoked_Call) Run(run func(ctx context.Context, id string)) *MockSubscriptionRepository_MarkRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSubscriptionRepository_MarkRevoked_Call) Return(_a0 error) *MockSubscriptionRepository_MarkRevoked_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscriptionRepository_MarkRevoked_Call) RunAndReturn(run func(context.Context, string) error) *MockSubscriptionRepository_MarkRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllByUser provides a mock function with given fields: ctx, userID
func (_m *MockSubscriptionRepository) RevokeAllByUser(ctx context.Context, userID string) ([]store.NotificationSubscription, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllByUser")
	}

	var r0 []store.NotificationSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]store.NotificationSubscription, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []store.NotificationSubscription); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]store.NotificationSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepository_RevokeAllByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllByUser'
type MockSubscriptionRepository_RevokeAllByUser_Call struct {
	*mock.Call
}

// RevokeAllByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockSubscriptionRepository_Expecter) RevokeAllByUser(ctx interface{}, userID interface{}) *MockSubscriptionRepository_RevokeAllByUser_Call {
	return &MockSubscriptionRepository_RevokeAllByUser_Call{Call: _e.mock.On("RevokeAllByUser", ctx, userID)}
}

func (_c *MockSubscriptionRepository_RevokeAllByUser_Call) Run(run func(ctx context.Context, userID string)) *MockSubscriptionRepository_RevokeAllByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSubscriptionRepository_RevokeAllByUser_Call) Return(_a0 []store.NotificationSubscription, _a1 error) *MockSubscriptionRepository_RevokeAllByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepository_RevokeAllByUser_Call) RunAndReturn(run func(context.Context, string) ([]store.NotificationSubscription, error)) *MockSubscriptionRepository_RevokeAllByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionRepository creates a new instance of MockSubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
