// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockS3Repository is an autogenerated mock type for the S3Repository type
type MockS3Repository struct {
	mock.Mock
}

type MockS3Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockS3Repository) EXPECT() *MockS3Repository_Expecter {
	return &MockS3Repository_Expecter{mock: &_m.Mock}
}

// BucketExists provides a mock function with given fields: ctx
func (_m *MockS3Repository) BucketExists(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BucketExists")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockS3Repository_BucketExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BucketExists'
type MockS3Repository_BucketExists_Call struct {
	*mock.Call
}

// BucketExists is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockS3Repository_Expecter) BucketExists(ctx interface{}) *MockS3Repository_BucketExists_Call {
	return &MockS3Repository_BucketExists_Call{Call: _e.mock.On("BucketExists", ctx)}
}

func (_c *MockS3Repository_BucketExists_Call) Run(run func(ctx context.Context)) *MockS3Repository_BucketExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockS3Repository_BucketExists_Call) Return(_a0 error) *MockS3Repository_BucketExists_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockS3Repository_BucketExists_Call) RunAndReturn(run func(context.Context) error) *MockS3Repository_BucketExists_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, key, reader, size
func (_m *MockS3Repository) Upload(ctx context.Context, key string, reader io.Reader, size int64) (string, error) {
	ret := _m.Called(ctx, key, reader, size)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64) (string, error)); ok {
		return rf(ctx, key, reader, size)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, io.Reader, int64) string); ok {
		r0 = rf(ctx, key, reader, size)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, io.Reader, int64) error); ok {
		r1 = rf(ctx, key, reader, size)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockS3Repository_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockS3Repository_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - reader io.Reader
//   - size int64
func (_e *MockS3Repository_Expecter) Upload(ctx interface{}, key interface{}, reader interface{}, size interface{}) *MockS3Repository_Upload_Call {
	return &MockS3Repository_Upload_Call{Call: _e.mock.On("Upload", ctx, key, reader, size)}
}

func (_c *MockS3Repository_Upload_Call) Run(run func(ctx context.Context, key string, reader io.Reader, size int64)) *MockS3Repository_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(io.Reader), args[3].(int64))
	})
	return _c
}

func (_c *MockS3Repository_Upload_Call) Return(_a0 string, _a1 error) *MockS3Repository_Upload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockS3Repository_Upload_Call) RunAndReturn(run func(context.Context, string, io.Reader, int64) (string, error)) *MockS3Repository_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockS3Repository creates a new instance of MockS3Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockS3Repository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockS3Repository {
	mock := &MockS3Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
